import type { RepositorySnapshot } from './city';

const entries: Array<[string, number]> = [
  ['README.md', 7200],
  ['package.json', 1900],
  ['docker-compose.yml', 1300],
  ['.github/workflows/ci.yml', 1600],
  ['apps/web/src/app/page.tsx', 900],
  ['apps/web/src/app/layout.tsx', 1600],
  ['apps/web/src/app/globals.css', 22400],
  ['apps/web/src/components/dev-city-app.tsx', 35800],
  ['apps/web/src/components/repository-search.tsx', 8400],
  ['apps/web/src/components/city-canvas.tsx', 19300],
  ['apps/web/src/components/file-inspector.tsx', 7700],
  ['apps/web/src/lib/city.ts', 17800],
  ['apps/web/src/lib/github.ts', 6100],
  ['apps/web/src/lib/city.test.ts', 4800],
  ['apps/web/src/store/store.ts', 5200],
  ['apps/web/package.json', 1200],
  ['apps/web/tsconfig.json', 1000],
  ['apps/api/src/main.ts', 1100],
  ['apps/api/src/app.module.ts', 900],
  ['apps/api/src/repository.controller.ts', 3600],
  ['apps/api/src/repository.service.ts', 7800],
  ['apps/api/api/index.ts', 2100],
  ['apps/api/package.json', 1400],
  ['apps/api/tsconfig.json', 900],
  ['docs/architecture.md', 5300],
  ['docs/deployment.md', 4100],
  ['public/grid.svg', 1200],
  ['scripts/seed-city.ts', 3200],
  ['database/schema.sql', 9800],
  ['database/views.sql', 5400],
  ['packages/ui/button.tsx', 4300],
  ['packages/ui/panel.tsx', 6700],
  ['packages/ui/tooltip.tsx', 5100],
  ['packages/shared/types.ts', 8400],
  ['packages/shared/constants.ts', 2600],
  ['packages/shared/formatter.ts', 4900],
  ['tests/e2e/city.spec.ts', 7600],
  ['tests/e2e/search.spec.ts', 4300],
];

export const demoSnapshot: RepositorySnapshot = {
  owner: 'leoo1992',
  repo: 'DevCity',
  defaultBranch: 'main',
  description:
    'Transform GitHub repositories into interactive 3D cities.',
  stars: 24,
  forks: 4,
  url: 'https://github.com/leoo1992/DevCity',
  files: entries.map(([path, size], index) => ({
    path,
    size,
    sha: 'demo-' + index,
  })),
};
